version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(levelname)s: %(message)s'
filters:
  profileFilter:
    (): src.logging.ProfileFilter
    is_profile: True
  noProfileFilter:
    (): src.logging.ProfileFilter
    is_profile: False
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filters:
    - noProfileFilter
    filename: logs/tcp_sniffer.log
    maxBytes: 100000
    backupCount: 3
  profile:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filters:
    - profileFilter
    filename: logs/profiling.log
    maxBytes: 100000
    backupCount: 3
loggers:
  root:
    level: INFO
    handlers:
    - file
    - profile
